--create database
CREATE DATABASE IF NOT EXISTS GENERAL;
CREATE SCHEMA IF NOT EXISTS BRONZE;

CREATE TABLE IF NOT EXISTS BRONZE.CRYPTO_INGEST (
    RUN_ID       STRING,
    INGESTED_AT  TIMESTAMP_NTZ,
    PAYLOAD      VARCHAR
);
